title: Henrique Vianna
description: Greetings, Programs!
plugins:
  - jemoji
remote_theme: pmarsceill/just-the-docs

# Just the Docs theme options
logo: "/img/audioMotion-logo.png"
footer_content: "Copyright &copy; 2018-2020 Henrique Avila Vianna."
color_scheme: "dark"
aux_links:
  "Demo":
    - "https://audiomotion.me/public/"
  "Download":
    - "https://github.com/hvianna/audioMotion.js/releases"
  "View on GitHub":
    - "https://github.com/hvianna/hvianna.github.io"
